//
//  cardStore.swift
//  Frost_digital_sheets
//
//  Created by Hackin Tosh on 2/26/23.
//

import Foundation

var cardStore: [String: [Card]] = [
    "boneshaper": [
        Card(id: UUID(), name: "Wrath Of The Turned Earth", imgName: "Wrath_Of_The_Turned_Earth", level: 0, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 80), Card(id: UUID(), name: "Approach Oblivion", imgName: "Approach_Oblivion", level: 0, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 53),
        Card(id: UUID(), name: "Exploding Corpse", imgName: "Exploding_Corpse", level: 0, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 21), Card(id: UUID(), name: "Life In Death", imgName: "Life_In_Death", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 91),
                                                      Card(id: UUID(), name: "Returned Servant", imgName: "Returned_Servant", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 81),
                                                       Card(id: UUID(), name: "Damned Horde", imgName: "Damned_Horde", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 71),
        Card(id: UUID(), name: "Transfer Of Essence", imgName: "Transfer_Of_Essence", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 62),Card(id: UUID(), name: "Decaying Will", imgName:"Decaying_Will", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 46),
        Card(id: UUID(), name: "Dark Tidings", imgName: "Dark_Tidings", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 43),Card(id: UUID(), name: "Angry Spirits", imgName: "Angry_Spirits", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 76),
        Card(id: UUID(), name: "Fell Remedy", imgName: "Fell_Remedy", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 30),Card(id: UUID(), name: "Flow Of The Black River", imgName: "Flow_Of_The_Black_River", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 18),
        Card(id: UUID(), name: "Command The Wretched", imgName: "Command_The_Wretched", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 83),Card(id: UUID(), name: "Eternal Torment", imgName: "Eternal_Torment", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 70),
        Card(id: UUID(), name: "Malicious Conversion", imgName: "Malicious_Conversion", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 26),Card(id: UUID(), name: "Unearthed Horror", imgName: "Unearthed_Horror", level: 2, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 94),
        Card(id: UUID(), name: "Bone Dagger", imgName: "Bone_Dagger", level: 2, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 29),Card(id: UUID(), name: "Grave Digging", imgName: "Grave_Digging", level: 3, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 96),
                                                      Card(id: UUID(), name: "Putrid Cloud", imgName: "Putrid_Cloud", level: 3, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 28),Card(id: UUID(), name: "Critical Failure", imgName: "Critical_Failure", level: 4, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 95),
                                                      Card(id: UUID(), name: "Flesh Shield", imgName: "Flesh_Shield", level: 4, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 16),Card(id: UUID(), name: "Unforgivable Methods", imgName: "Unforgiveable_Methods", level: 5, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 98),
                                                      Card(id: UUID(), name: "Solid Bones", imgName: "Solid_Bones", level: 5, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 32),Card(id: UUID(), name: "Rotting Multitude", imgName: "Rotting_Multitude", level: 6, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 66),
        Card(id: UUID(), name: "Twisted Decree", imgName: "Twisted_Decree", level: 6, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 85),Card(id: UUID(), name: "Recycled Limbs", imgName: "Recycled_Limbs", level: 7, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 52),
        Card(id: UUID(), name: "Soul Claim", imgName: "Soul_Claim", level: 7, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 23),Card(id: UUID(), name: "Endless Numbers", imgName:"Endless_Numbers", level: 8, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 86),
                                                      Card(id: UUID(), name: "Wailing From Beyond", imgName: "Wailing_From_Beyond", level: 8, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 73),Card(id: UUID(), name: "Unholy Prowess", imgName: "Unholy_Prowess", level: 9, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 97),
                                                      Card(id: UUID(), name: "Behold The Shrouded Sun", imgName: "Behold_The_Shrouded_Sun", level: 9, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 10)
    ],
        
    "bannerspear": [
        Card(id: UUID(), name: "Resolved Courage", imgName: "Resolved_Courage", level: 0, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 10),  Card(id: UUID(), name: "Driving Inspiration", imgName: "Driving_Inspiration", level: 0, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 18),
        Card(id: UUID(), name: "Incendiary Throw", imgName: "Incendiary_Throw", level: 0, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 22), Card(id: UUID(), name: "At All Costs", imgName: "At_All_Costs", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 60),
                                                      Card(id: UUID(), name: "Rallying Cry", imgName: "Rallying_Cry", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 71),
         Card(id: UUID(), name: "Unbreakable Wall", imgName: "Unbreakable_Wall", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 83),
                                                      Card(id: UUID(), name: "Javelin", imgName: "Javelin", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 21),Card(id: UUID(), name: "Deflecting Maneuver", imgName: "Deflecting_Maneuver", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 15),
        Card(id: UUID(), name: "Tip Of The Spear", imgName: "Tip_Of_The_Spear", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 67),Card(id: UUID(), name: "Combined Effort", imgName: "Combined_Effort", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 32),
        Card(id: UUID(), name: "Set For The Charge", imgName: "Set_For_The_Charge", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 06),Card(id: UUID(), name: "Pincer Movement", imgName: "Pincer_Movement", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 69),
                                                      Card(id: UUID(), name: "Regroup", imgName: "Regroup", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 25),Card(id: UUID(), name: "Meat Grinder", imgName: "Meat_Grinder", level: 2, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 62),
        Card(id: UUID(), name: "Pinning Charge", imgName: "Pinning_Charge", level: 2, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 17),Card(id: UUID(), name: "Let Them Come", imgName: "Let_Them_Come", level: 3, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 24),
                                                      Card(id: UUID(), name: "Head Of The Hammer", imgName: "Head_Of_The_Hammer", level: 3, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 87),Card(id: UUID(), name: "Boldening Blow", imgName: "Boldening_Blow", level: 4, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 72),
                                                      Card(id: UUID(), name: "Air Support", imgName: "Air_Support", level: 4, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 20),Card(id: UUID(), name: "Explosive Epicenter", imgName: "Explosive_Epicenter", level: 5, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 78),
                                                      Card(id: UUID(), name: "Hold The Line", imgName: "Hold_The_Line", level: 5, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 05),Card(id: UUID(), name: "Barricade", imgName: "Barricade", level: 6, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 16),
        Card(id: UUID(), name: "Bolstering Shout", imgName: "Bolstering_Shout", level: 6, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 75),Card(id: UUID(), name: "Tri-Thrust", imgName: "Tri_Thrust", level: 7, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 27),
                                                      Card(id: UUID(), name: "Lead From Afar", imgName: "Lead_From_Afar", level: 7, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 80),Card(id: UUID(), name: "Sweeping Aid", imgName: "Sweeping_Aid", level: 8, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 73),
        Card(id: UUID(), name: "Taunting Howl", imgName: "Taunting_Howl", level: 8, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 11),Card(id: UUID(), name: "Take No Prisoners", imgName: "Take_No_Prisoners", level: 9, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 85),
                                                      Card(id: UUID(), name: "Hail Of Spears", imgName: "Hail_Of_Spears", level: 9, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 44)
        
    ],
    
    "drifter" : [
        Card(id: UUID(), name: "No Remorse", imgName: "No_Remorse", level: 0, Unlocked: true, PlayableClass: "drifter", initiativeVal: 20), Card(id: UUID(), name: "Fortitude", imgName: "Fortitude", level: 0, Unlocked: true, PlayableClass: "drifter", initiativeVal: 31),
        Card(id: UUID(), name: "Destructive Fury", imgName: "Destructive_Fury", level: 0, Unlocked: true, PlayableClass: "drifter", initiativeVal: 19),
        Card(id: UUID(), name: "Crushing Weight", imgName: "Crushing_Weight", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 71),Card(id: UUID(), name: "Sustained Momentum", imgName: "Sustained_Momentum", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 76),
        Card(id: UUID(), name: "Precision Aim", imgName: "Precision_Aim", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 76),Card(id: UUID(), name: "Continuous Health", imgName: "Continuous_Health", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 61),
        Card(id: UUID(), name: "Relentless", imgName: "Relentless", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 89),Card(id: UUID(), name: "Unbreakable", imgName: "Unbreakable", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 90),
        Card(id: UUID(), name: "Vile Assault", imgName: "Vile_Assault", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 27),Card(id: UUID(), name: "Draining Arrows", imgName: "Draining_Arrows", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 23),
        Card(id: UUID(), name: "Prudent Preparation", imgName: "Prudent_Preparation", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 14),Card(id: UUID(), name: "Deadly Shot", imgName: "Deadly_Shot", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 32),
        Card(id: UUID(), name: "Bloodletting", imgName: "Bloodletting", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 65),Card(id: UUID(), name: "Violent Inheritance", imgName: "Violent_Inheritance", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 70),
        Card(id: UUID(), name: "Shockwave", imgName: "Shockwave", level: 2, Unlocked: false, PlayableClass: "drifter", initiativeVal: 17),
        Card(id: UUID(), name: "Ever Forward", imgName: "Ever_Forward", level: 2, Unlocked: false, PlayableClass: "drifter", initiativeVal: 67),Card(id: UUID(), name: "Fierce Barrage", imgName: "Fierce_Barrage", level: 3, Unlocked: false, PlayableClass: "drifter", initiativeVal: 32),
        Card(id: UUID(), name: "Dual Bow", imgName: "Dual_Bow", level: 3, Unlocked: false, PlayableClass: "drifter", initiativeVal: 26),Card(id: UUID(), name: "Chunk Of Flesh", imgName: "Chunk_Of_Flesh", level: 4, Unlocked: false, PlayableClass: "drifter", initiativeVal: 62),
        Card(id: UUID(), name: "Gift Of The Prey", imgName: "Gift_Of_The_Prey", level: 4, Unlocked: false, PlayableClass: "drifter", initiativeVal: 40),Card(id: UUID(), name: "Survivalist", imgName: "Survivalist", level: 5, Unlocked: false, PlayableClass: "drifter", initiativeVal: 91),
        Card(id: UUID(), name: "Break Through", imgName: "Break_Through",  level: 5, Unlocked: false, PlayableClass: "drifter", initiativeVal: 34),Card(id: UUID(), name: "Accurate Strikes", imgName: "Accurate_Strikes", level: 6, Unlocked: false, PlayableClass: "drifter", initiativeVal: 56),
        Card(id: UUID(), name: "Consume Stamina", imgName: "Consume_Stamina", level: 6, Unlocked: false, PlayableClass: "drifter", initiativeVal: 21),
        Card(id: UUID(), name: "Like the Wind",  imgName: "Like_The_Wind", level: 7, Unlocked: false, PlayableClass: "drifter", initiativeVal: 77),
        Card(id: UUID(), name: "Unending Fight", imgName: "Unending_Fight",  level: 7, Unlocked: false, PlayableClass: "drifter", initiativeVal: 25),Card(id: UUID(), name: "Against All Odds", imgName: "Against_All_Odds", level: 8, Unlocked: false, PlayableClass: "drifter", initiativeVal: 37),
        Card(id: UUID(), name: "Inevitable Conclusion", imgName: "Inevitable_Conclusion",  level: 8, Unlocked: false, PlayableClass: "drifter", initiativeVal: 29),Card(id: UUID(), name: "Everlasting", imgName: "Everlasting",  level: 9, Unlocked: false, PlayableClass: "drifter", initiativeVal: 96),
        Card(id: UUID(), name: "Use Every Part", imgName: "Use_Every_Part", level: 9, Unlocked: false, PlayableClass: "drifter", initiativeVal: 18),
    ],
    
    "geminate": [
        Card(id: UUID(), name: "Smoldering Hatred", imgName: "Smoldering_Hatred", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 32),  Card(id: UUID(), name: "Reckless Jab", imgName: "Reckless_Jab", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 38),
        Card(id: UUID(), name: "Reshape The Guise", imgName: "Reshape_The_Guise", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 38), Card(id: UUID(), name: "Feeding Frenzy", imgName: "Feeding_Frenzy", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 62),
        Card(id: UUID(), name: "Icebound Quills", imgName: "Icebound_Quills", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 14),
        Card(id: UUID(), name: "Draining Pincers", imgName: "Draining_Pincers", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 72),
        Card(id: UUID(), name: "Hornet Stingers", imgName: "Hornet_Stingers", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 23),
        Card(id: UUID(), name: "Changeling's Boon", imgName: "Changeling's_Boon", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 40),Card(id: UUID(), name: "Flailing Tendrils", imgName: "Flailing_Tendrils", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 12),
        Card(id: UUID(), name: "Drag Down", imgName: "Drag_Down", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 34),Card(id: UUID(), name: "Hornbeetle Carapace", imgName: "Hornbeetle_Carapace", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 20),
        Card(id: UUID(), name: "Selfless Offering", imgName: "Selfless_Offering", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 27),Card(id: UUID(), name: "Into My Embrace", imgName: "Into_My_Embrace", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 36),
        Card(id: UUID(), name: "Firefly Swarm", imgName: "Firefly_Swarm", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 76),Card(id: UUID(), name: "Scarab Flight", imgName: "Scarab_Flight", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 30),
        Card(id: UUID(), name: "Harvest the Essence", imgName: "Harvest_The_Essence", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 60),Card(id: UUID(), name: "Hail Of Thorns", imgName: "Hail_Of_Thorns", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 88),
        Card(id: UUID(), name: "Mind Spike", imgName: "Mind_Spike", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 18),Card(id: UUID(), name: "Venomous Barbs", imgName: "Venomous_Barbs", level: 2, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 17),
        Card(id: UUID(), name: "Locust Host", imgName: "Locust_Host", level: 2, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 23),Card(id: UUID(), name: "Mandible Storm", imgName: "Mandible_Storm", level: 3, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 30),
        Card(id: UUID(), name: "Dragonfly Surge", imgName: "Dragonfly_Surge", level: 3, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 50),Card(id: UUID(), name: "Thresh And Flail", imgName: "Thresh_And_Flail", level: 4, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 43),
        Card(id: UUID(), name: "Luminous Descent", imgName: "Luminous_Descent", level: 4, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 67),Card(id: UUID(), name: "Formless Grace", imgName: "Formless_Grace", level: 5, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 75),
        Card(id: UUID(), name: "Chitinous Horde", imgName: "Chitinous_Horde", level: 5, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 15),Card(id: UUID(), name: "Corrosive Acids", imgName: "Corrosive_Acids", level: 6, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 28),
        Card(id: UUID(), name: "Hirudotherapy", imgName: "Hirudotherapy", level: 6, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 92),Card(id: UUID(), name: "Two-Pronged Entrapment", imgName: "Two_Pronged_Entrapment", level: 7, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 21),
        Card(id: UUID(), name: "Alluring Pheromones", imgName: "Alluring_Pheromones", level: 7, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 49),Card(id: UUID(), name: "Accelerated Metabolism", imgName: "Accelerated_Metabolism", level: 8, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 85),
        Card(id: UUID(), name: "Oscillating Entity", imgName: "Oscillating_Entity", level: 8, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 55),Card(id: UUID(), name: "Harbinger Of Ruin", imgName: "Harbinger_Of_Ruin", level: 9, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 11),
        Card(id: UUID(), name: "Voice Of Salvation", imgName: "Voice_Of_Salvation", level: 9, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 39)
    ],
    "blinkblade": [
        Card(id: UUID(), name: "Experimental Adjustment", imgName: "Experimental_Adjustment", level: 0, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 12), Card(id: UUID(), name: "Borrowed Time", imgName: "Borrowed_Time", level: 0, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 02),
        Card(id: UUID(), name: "Sand In The Hourglass", imgName: "Sand_In_The_Hourglass", level: 0, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 52), Card(id: UUID(), name: "Blurry Jab", imgName: "Blurry_Jab", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 20),
        Card(id: UUID(), name: "Twin Strike", imgName: "Twin_Strike", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 24), Card(id: UUID(), name: "Sap Speed", imgName: "Sap_Speed", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 45),
        Card(id: UUID(), name: "Kinetic Transfer", imgName: "Kinetic_Transfer", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 36),Card(id: UUID(), name: "Overdrive", imgName: "Overdrive", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 60),
        Card(id: UUID(), name: "Power Leak", imgName: "Power_Leak", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 17),Card(id: UUID(), name: "Hit And Run", imgName: "Hit_And_Run", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 41),
        Card(id: UUID(), name: "Drive Recharge", imgName: "Drive_Recharge", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 69),Card(id: UUID(), name: "Cascading Reaction", imgName: "Cascading_Reaction", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 19),
        Card(id: UUID(), name: "Temporal Displacement", imgName: "Temporal_Displacement", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 44),Card(id: UUID(), name: "Systems Reboot", imgName: "Systems_Reboot", level: 2, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 57),
        Card(id: UUID(), name: "Reckless Augmentation", imgName: "Reckless_Augmentation", level: 2, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 10),Card(id: UUID(), name: "Make It Count", imgName: "Make_It_Count", level: 3, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 51),
        Card(id: UUID(), name: "Double Time", imgName: "Double_Time", level: 3, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 22),Card(id: UUID(), name: "Precision Timing", imgName: "Precision_Timing", level: 4, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 15),
        Card(id: UUID(), name: "Potential Energy", imgName: "Potential_Energy", level: 4, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 32),Card(id: UUID(), name: "Breakneck Speed", imgName: "Breakneck_Speed", level: 5, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 03),
        Card(id: UUID(), name: "Flashing Flurry", imgName: "Flashing_Flurry", level: 5, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 40),Card(id: UUID(), name: "Stab Them All", imgName: "Stab_Them_All", level: 6, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 04),
        Card(id: UUID(), name: "The Knife's Edge", imgName: "The_Knife's_Edge", level: 6, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 65),Card(id: UUID(), name: "Phasing Blades", imgName: "Phasing_Blades", level: 7, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 63),
        Card(id: UUID(), name: "Rushed To The End", imgName: "Rushed_To_The_End", level: 7, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 32),Card(id: UUID(), name: "Quantum Uncertainty", imgName: "Quantum_Uncertainty", level: 8, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 35),
        Card(id: UUID(), name: "Fastest Alive", imgName: "Fastest_Alive", level: 8, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 01),Card(id: UUID(), name: "Reverse The Flow", imgName: "Reverse_The_Flow", level: 9, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 58),
        Card(id: UUID(), name: "Fractured Timeline", imgName: "Fractured_Timeline", level: 9, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 55)
    ],
    "deathwalker": [
        Card(id: UUID(), name: "Wave Of Anguish", imgName: "Wave_Of_Anguish", level: 0, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 58), Card(id: UUID(), name: "Rest In The Shade", imgName: "Rest_In_The_Shade", level: 0, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 26),
        Card(id: UUID(), name: "Forceful Spirits", imgName: "Forceful_Spirits", level: 0, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 34), Card(id: UUID(), name: "Call To The Abyss", imgName: "Call_To_The_Abyss", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 82),
        Card(id: UUID(), name: "Anger Of The Dead", imgName: "Anger_Of_The_Dead", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 14), Card(id: UUID(), name: "Sunless Apparition", imgName: "Sunless_Apparition", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 96),
        Card(id: UUID(), name: "Fluid Night", imgName: "Fluid_Night",  level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 24),Card(id: UUID(), name: "Dark Fog", imgName: "Dark_Fog", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 46),
        Card(id: UUID(), name: "Black Barrage", imgName: "Black_Barrage", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 28),Card(id: UUID(), name: "Call Of Doom", imgName: "Call_Of_Doom", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 32),
        Card(id: UUID(), name: "Eclipse", imgName: "Eclipse", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 86),Card(id: UUID(), name: "Lingering Rot", imgName: "Lingering_Rot", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 64),
        Card(id: UUID(), name: "Shadow Step", imgName: "Shadow_Step", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 19),Card(id: UUID(), name: "Strength Of The Abyss", imgName: "Strength_Of_The_Abyss", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 50),
        Card(id: UUID(), name: "Restless Spirits", imgName: "Restless_Spirits", level: 2, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 20),
        Card(id: UUID(), name: "Deepening Despair", imgName: "Deepening_Despair", level: 2, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 11),Card(id: UUID(), name: "Dead Bolt", imgName: "Dead_Bolt", level: 3, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 88),
        Card(id: UUID(), name: "Ritual Sacrifice", imgName: "Ritual_Sacrifice", level: 3, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 13),Card(id: UUID(), name: "Fleeting Dusk", imgName: "Fleeting_Dusk", level: 4, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 36),
        Card(id: UUID(), name: "Pulled Across", imgName: "Pulled_Across", level: 4, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 77),Card(id: UUID(), name: "Medium", imgName: "Medium", level: 5, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 55),
        Card(id: UUID(), name: "Dominate", imgName: "Dominate", level: 5, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 29),Card(id: UUID(), name: "The Night Takes Shape", imgName: "The_Night_Takes_Shape", level: 6, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 94),
        Card(id: UUID(), name: "Vengeful Storm", imgName: "Vengeful_Storm", level: 6, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 18),Card(id: UUID(), name: "Proliferation Of The Abyss", imgName: "Proliferation_Of_The_Abyss", level: 7, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 38),
        Card(id: UUID(), name: "Hungry Grasps", imgName: "Hungry_Grasps", level: 7, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 25),Card(id: UUID(), name: "Lashing Tendrils", imgName: "Lashing_Tendrils", level: 8, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 80),
        Card(id: UUID(), name: "Frozen In Fear", imgName: "Frozen_In_Fear", level: 8, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 21),Card(id: UUID(), name: "When Your Time Comes", imgName: "When_Your_Time_Comes", level: 9, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 72),
        Card(id: UUID(), name: "Black Lance", imgName: "Black_Lance", level: 9, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 16)
    ],
]

