//
//  cardStore.swift
//  Frost_digital_sheets
//
//  Created by Hackin Tosh on 2/26/23.
//

import Foundation

var cardStore: [String: [Card]] = [
    "boneshaper": [
        Card(id: UUID(), name: "Wrath Of The Turned Earth", imgName: "Wrath_Of_The_Turned_Earth", level: 0, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 80), Card(id: UUID(), name: "Approach Oblivion", imgName: "Approach_Oblivion", level: 0, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 53),
        Card(id: UUID(), name: "Exploding Corpse", imgName: "Exploding_Corpse", level: 0, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 21), Card(id: UUID(), name: "Life In Death", imgName: "Life_In_Death", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 91),
                                                      Card(id: UUID(), name: "Returned Servant", imgName: "Returned_Servant", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 81),
                                                       Card(id: UUID(), name: "Damned Horde", imgName: "Damned_Horde", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 71),
        Card(id: UUID(), name: "Transfer Of Essence", imgName: "Transfer_Of_Essence", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 62),Card(id: UUID(), name: "Decaying Will", imgName:"Decaying_Will", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 46),
        Card(id: UUID(), name: "Dark Tidings", imgName: "Dark_Tidings", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 43),Card(id: UUID(), name: "Angry Spirits", imgName: "Angry_Spirits", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 76),
        Card(id: UUID(), name: "Fell Remedy", imgName: "Fell_Remedy", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 30),Card(id: UUID(), name: "Flow Of The Black River", imgName: "Flow_Of_The_Black_River", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 18),
        Card(id: UUID(), name: "Command The Wretched", imgName: "Command_The_Wretched", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 83),Card(id: UUID(), name: "Eternal Torment", imgName: "Eternal_Torment", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 70),
        Card(id: UUID(), name: "Malicious Conversion", imgName: "Malicious_Conversion", level: 1, Unlocked: true, PlayableClass: "Boneshaper", initiativeVal: 26),Card(id: UUID(), name: "Unearthed Horror", imgName: "Unearthed_Horror", level: 2, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 94),
        Card(id: UUID(), name: "Bone Dagger", imgName: "Bone_Dagger", level: 2, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 29),Card(id: UUID(), name: "Grave Digging", imgName: "Grave_Digging", level: 3, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 96),
                                                      Card(id: UUID(), name: "Putrid Cloud", imgName: "Putrid_Cloud", level: 3, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 28),Card(id: UUID(), name: "Critical Failure", imgName: "Critical_Failure", level: 4, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 95),
                                                      Card(id: UUID(), name: "Flesh Shield", imgName: "Flesh_Shield", level: 4, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 16),Card(id: UUID(), name: "Unforgivable Methods", imgName: "Unforgiveable_Methods", level: 5, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 98),
                                                      Card(id: UUID(), name: "Solid Bones", imgName: "Solid_Bones", level: 5, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 32),Card(id: UUID(), name: "Rotting Multitude", imgName: "Rotting_Multitude", level: 6, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 66),
        Card(id: UUID(), name: "Twisted Decree", imgName: "Twisted_Decree", level: 6, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 85),Card(id: UUID(), name: "Recycled Limbs", imgName: "Recycled_Limbs", level: 7, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 52),
        Card(id: UUID(), name: "Soul Claim", imgName: "Soul_Claim", level: 7, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 23),Card(id: UUID(), name: "Endless Numbers", imgName:"Endless_Numbers", level: 8, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 86),
                                                      Card(id: UUID(), name: "Wailing From Beyond", imgName: "Wailing_From_Beyond", level: 8, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 73),Card(id: UUID(), name: "Unholy Prowess", imgName: "Unholy_Prowess", level: 9, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 97),
                                                      Card(id: UUID(), name: "Behold The Shrouded Sun", imgName: "Behold_The_Shrouded_Sun", level: 9, Unlocked: false, PlayableClass: "Boneshaper", initiativeVal: 10)
    ],
        
    "bannerspear": [
        Card(id: UUID(), name: "Resolved Courage", imgName: "Resolved_Courage", level: 0, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 10),  Card(id: UUID(), name: "Driving Inspiration", imgName: "Driving_Inspiration", level: 0, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 18),
        Card(id: UUID(), name: "Incendiary Throw", imgName: "Incendiary_Throw", level: 0, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 22), Card(id: UUID(), name: "At All Costs", imgName: "At_All_Costs", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 60),
                                                      Card(id: UUID(), name: "Rallying Cry", imgName: "Rallying_Cry", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 71),
         Card(id: UUID(), name: "Unbreakable Wall", imgName: "Unbreakable_Wall", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 83),
                                                      Card(id: UUID(), name: "Javelin", imgName: "Javelin", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 21),Card(id: UUID(), name: "Deflecting Maneuver", imgName: "Deflecting_Maneuver", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 15),
        Card(id: UUID(), name: "Tip Of The Spear", imgName: "Tip_Of_The_Spear", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 67),Card(id: UUID(), name: "Combined Effort", imgName: "Combined_Effort", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 32),
        Card(id: UUID(), name: "Set For The Charge", imgName: "Set_For_The_Charge", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 06),Card(id: UUID(), name: "Pincer Movement", imgName: "Pincer_Movement", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 69),
                                                      Card(id: UUID(), name: "Regroup", imgName: "Regroup", level: 1, Unlocked: true, PlayableClass: "Banner Spear", initiativeVal: 25),Card(id: UUID(), name: "Meat Grinder", imgName: "Meat_Grinder", level: 2, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 62),
        Card(id: UUID(), name: "Pinning Charge", imgName: "Pinning_Charge", level: 2, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 17),Card(id: UUID(), name: "Let Them Come", imgName: "Let_Them_Come", level: 3, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 24),
                                                      Card(id: UUID(), name: "Head Of The Hammer", imgName: "Head_Of_The_Hammer", level: 3, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 87),Card(id: UUID(), name: "Boldening Blow", imgName: "Boldening_Blow", level: 4, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 72),
                                                      Card(id: UUID(), name: "Air Support", imgName: "Air_Support", level: 4, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 20),Card(id: UUID(), name: "Explosive Epicenter", imgName: "Explosive_Epicenter", level: 5, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 78),
                                                      Card(id: UUID(), name: "Hold The Line", imgName: "Hold_The_Line", level: 5, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 05),Card(id: UUID(), name: "Barricade", imgName: "Barricade", level: 6, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 16),
        Card(id: UUID(), name: "Bolstering Shout", imgName: "Bolstering_Shout", level: 6, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 75),Card(id: UUID(), name: "Tri-Thrust", imgName: "Tri_Thrust", level: 7, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 27),
                                                      Card(id: UUID(), name: "Lead From Afar", imgName: "Lead_From_Afar", level: 7, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 80),Card(id: UUID(), name: "Sweeping Aid", imgName: "Sweeping_Aid", level: 8, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 73),
        Card(id: UUID(), name: "Taunting Howl", imgName: "Taunting_Howl", level: 8, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 11),Card(id: UUID(), name: "Take No Prisoners", imgName: "Take_No_Prisoners", level: 9, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 85),
                                                      Card(id: UUID(), name: "Hail Of Spears", imgName: "Hail_Of_Spears", level: 9, Unlocked: false, PlayableClass: "Banner Spear", initiativeVal: 44)
        
    ],
    
    "drifter" : [
        Card(id: UUID(), name: "No Remorse", imgName: "No_Remorse", level: 0, Unlocked: true, PlayableClass: "drifter", initiativeVal: 20), Card(id: UUID(), name: "Fortitude", imgName: "Fortitude", level: 0, Unlocked: true, PlayableClass: "drifter", initiativeVal: 31),
        Card(id: UUID(), name: "Destructive Fury", imgName: "Destructive_Fury", level: 0, Unlocked: true, PlayableClass: "drifter", initiativeVal: 19),
        Card(id: UUID(), name: "Crushing Weight", imgName: "Crushing_Weight", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 71),Card(id: UUID(), name: "Sustained Momentum", imgName: "Sustained_Momentum", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 76),
        Card(id: UUID(), name: "Precision Aim", imgName: "Precision_Aim", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 76),Card(id: UUID(), name: "Continuous Health", imgName: "Continuous_Health", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 61),
        Card(id: UUID(), name: "Relentless", imgName: "Relentless", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 89),Card(id: UUID(), name: "Unbreakable", imgName: "Unbreakable", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 90),
        Card(id: UUID(), name: "Vile Assault", imgName: "Vile_Assault", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 27),Card(id: UUID(), name: "Draining Arrows", imgName: "Draining_Arrows", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 23),
        Card(id: UUID(), name: "Prudent Preparation", imgName: "Prudent_Preparation", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 14),Card(id: UUID(), name: "Deadly Shot", imgName: "Deadly_Shot", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 32),
        Card(id: UUID(), name: "Bloodletting", imgName: "Bloodletting", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 65),Card(id: UUID(), name: "Violent Inheritance", imgName: "Violent_Inheritance", level: 1, Unlocked: true, PlayableClass: "drifter", initiativeVal: 70),
        Card(id: UUID(), name: "Shockwave", imgName: "Shockwave", level: 2, Unlocked: false, PlayableClass: "drifter", initiativeVal: 17),
        Card(id: UUID(), name: "Ever Forward", imgName: "Ever_Forward", level: 2, Unlocked: false, PlayableClass: "drifter", initiativeVal: 67),Card(id: UUID(), name: "Fierce Barrage", imgName: "Fierce_Barrage", level: 3, Unlocked: false, PlayableClass: "drifter", initiativeVal: 32),
        Card(id: UUID(), name: "Dual Bow", imgName: "Dual_Bow", level: 3, Unlocked: false, PlayableClass: "drifter", initiativeVal: 26),Card(id: UUID(), name: "Chunk Of Flesh", imgName: "Chunk_Of_Flesh", level: 4, Unlocked: false, PlayableClass: "drifter", initiativeVal: 62),
        Card(id: UUID(), name: "Gift Of The Prey", imgName: "Gift_Of_The_Prey", level: 4, Unlocked: false, PlayableClass: "drifter", initiativeVal: 40),Card(id: UUID(), name: "Survivalist", imgName: "Survivalist", level: 5, Unlocked: false, PlayableClass: "drifter", initiativeVal: 91),
        Card(id: UUID(), name: "Break Through", imgName: "Break_Through",  level: 5, Unlocked: false, PlayableClass: "drifter", initiativeVal: 34),Card(id: UUID(), name: "Accurate Strikes", imgName: "Accurate_Strikes", level: 6, Unlocked: false, PlayableClass: "drifter", initiativeVal: 56),
        Card(id: UUID(), name: "Consume Stamina", imgName: "Consume_Stamina", level: 6, Unlocked: false, PlayableClass: "drifter", initiativeVal: 21),
        Card(id: UUID(), name: "Like the Wind",  imgName: "Like_The_Wind", level: 7, Unlocked: false, PlayableClass: "drifter", initiativeVal: 77),
        Card(id: UUID(), name: "Unending Fight", imgName: "Unending_Fight",  level: 7, Unlocked: false, PlayableClass: "drifter", initiativeVal: 25),Card(id: UUID(), name: "Against All Odds", imgName: "Against_All_Odds", level: 8, Unlocked: false, PlayableClass: "drifter", initiativeVal: 37),
        Card(id: UUID(), name: "Inevitable Conclusion", imgName: "Inevitable_Conclusion",  level: 8, Unlocked: false, PlayableClass: "drifter", initiativeVal: 29),Card(id: UUID(), name: "Everlasting", imgName: "Everlasting",  level: 9, Unlocked: false, PlayableClass: "drifter", initiativeVal: 96),
        Card(id: UUID(), name: "Use Every Part", imgName: "Use_Every_Part", level: 9, Unlocked: false, PlayableClass: "drifter", initiativeVal: 18),
    ],
    
    "geminate": [
        Card(id: UUID(), name: "Smoldering Hatred", imgName: "Smoldering_Hatred", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 32),  Card(id: UUID(), name: "Reckless Jab", imgName: "Reckless_Jab", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 38),
        Card(id: UUID(), name: "Reshape The Guise", imgName: "Reshape_The_Guise", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 38), Card(id: UUID(), name: "Feeding Frenzy", imgName: "Feeding_Frenzy", level: 0, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 62),
        Card(id: UUID(), name: "Icebound Quills", imgName: "Icebound_Quills", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 14),
        Card(id: UUID(), name: "Draining Pincers", imgName: "Draining_Pincers", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 72),
        Card(id: UUID(), name: "Hornet Stingers", imgName: "Hornet_Stingers", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 23),
        Card(id: UUID(), name: "Changeling's Boon", imgName: "Changeling's_Boon", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 40),Card(id: UUID(), name: "Flailing Tendrils", imgName: "Flailing_Tendrils", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 12),
        Card(id: UUID(), name: "Drag Down", imgName: "Drag_Down", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 34),Card(id: UUID(), name: "Hornbeetle Carapace", imgName: "Hornbeetle_Carapace", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 20),
        Card(id: UUID(), name: "Selfless Offering", imgName: "Selfless_Offering", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 27),Card(id: UUID(), name: "Into My Embrace", imgName: "Into_My_Embrace", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 36),
        Card(id: UUID(), name: "Firefly Swarm", imgName: "Firefly_Swarm", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 76),Card(id: UUID(), name: "Scarab Flight", imgName: "Scarab_Flight", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 30),
        Card(id: UUID(), name: "Harvest the Essence", imgName: "Harvest_The_Essence", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 60),Card(id: UUID(), name: "Hail Of Thorns", imgName: "Hail_Of_Thorns", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 88),
        Card(id: UUID(), name: "Mind Spike", imgName: "Mind_Spike", level: 1, Unlocked: true, PlayableClass: "Geminate", initiativeVal: 18),Card(id: UUID(), name: "Venomous Barbs", imgName: "Venomous_Barbs", level: 2, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 17),
        Card(id: UUID(), name: "Locust Host", imgName: "Locust_Host", level: 2, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 23),Card(id: UUID(), name: "Mandible Storm", imgName: "Mandible_Storm", level: 3, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 30),
        Card(id: UUID(), name: "Dragonfly Surge", imgName: "Dragonfly_Surge", level: 3, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 50),Card(id: UUID(), name: "Thresh And Flail", imgName: "Thresh_And_Flail", level: 4, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 43),
        Card(id: UUID(), name: "Luminous Descent", imgName: "Luminous_Descent", level: 4, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 67),Card(id: UUID(), name: "Formless Grace", imgName: "Formless_Grace", level: 5, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 75),
        Card(id: UUID(), name: "Chitinous Horde", imgName: "Chitinous_Horde", level: 5, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 15),Card(id: UUID(), name: "Corrosive Acids", imgName: "Corrosive_Acids", level: 6, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 28),
        Card(id: UUID(), name: "Hirudotherapy", imgName: "Hirudotherapy", level: 6, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 92),Card(id: UUID(), name: "Two-Pronged Entrapment", imgName: "Two_Pronged_Entrapment", level: 7, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 21),
        Card(id: UUID(), name: "Alluring Pheromones", imgName: "Alluring_Pheromones", level: 7, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 49),Card(id: UUID(), name: "Accelerated Metabolism", imgName: "Accelerated_Metabolism", level: 8, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 85),
        Card(id: UUID(), name: "Oscillating Entity", imgName: "Oscillating_Entity", level: 8, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 55),Card(id: UUID(), name: "Harbinger Of Ruin", imgName: "Harbinger_Of_Ruin", level: 9, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 11),
        Card(id: UUID(), name: "Voice Of Salvation", imgName: "Voice_Of_Salvation", level: 9, Unlocked: false, PlayableClass: "Geminate", initiativeVal: 39)
    ],
    "blinkblade": [
        Card(id: UUID(), name: "Experimental Adjustment", imgName: "Experimental_Adjustment", level: 0, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 12), Card(id: UUID(), name: "Borrowed Time", imgName: "Borrowed_Time", level: 0, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 02),
        Card(id: UUID(), name: "Sand In The Hourglass", imgName: "Sand_In_The_Hourglass", level: 0, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 52), Card(id: UUID(), name: "Blurry Jab", imgName: "Blurry_Jab", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 20),
        Card(id: UUID(), name: "Twin Strike", imgName: "Twin_Strike", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 24), Card(id: UUID(), name: "Sap Speed", imgName: "Sap_Speed", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 45),
        Card(id: UUID(), name: "Kinetic Transfer", imgName: "Kinetic_Transfer", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 36),Card(id: UUID(), name: "Overdrive", imgName: "Overdrive", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 60),
        Card(id: UUID(), name: "Power Leak", imgName: "Power_Leak", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 17),Card(id: UUID(), name: "Hit And Run", imgName: "Hit_And_Run", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 41),
        Card(id: UUID(), name: "Drive Recharge", imgName: "Drive_Recharge", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 69),Card(id: UUID(), name: "Cascading Reaction", imgName: "Cascading_Reaction", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 19),
        Card(id: UUID(), name: "Temporal Displacement", imgName: "Temporal_Displacement", level: 1, Unlocked: true, PlayableClass: "Blinkblade", initiativeVal: 44),Card(id: UUID(), name: "Systems Reboot", imgName: "Systems_Reboot", level: 2, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 57),
        Card(id: UUID(), name: "Reckless Augmentation", imgName: "Reckless_Augmentation", level: 2, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 10),Card(id: UUID(), name: "Make It Count", imgName: "Make_It_Count", level: 3, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 51),
        Card(id: UUID(), name: "Double Time", imgName: "Double_Time", level: 3, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 22),Card(id: UUID(), name: "Precision Timing", imgName: "Precision_Timing", level: 4, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 15),
        Card(id: UUID(), name: "Potential Energy", imgName: "Potential_Energy", level: 4, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 32),Card(id: UUID(), name: "Breakneck Speed", imgName: "Breakneck_Speed", level: 5, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 03),
        Card(id: UUID(), name: "Flashing Flurry", imgName: "Flashing_Flurry", level: 5, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 40),Card(id: UUID(), name: "Stab Them All", imgName: "Stab_Them_All", level: 6, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 04),
        Card(id: UUID(), name: "The Knife's Edge", imgName: "The_Knife's_Edge", level: 6, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 65),Card(id: UUID(), name: "Phasing Blades", imgName: "Phasing_Blades", level: 7, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 63),
        Card(id: UUID(), name: "Rushed To The End", imgName: "Rushed_To_The_End", level: 7, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 32),Card(id: UUID(), name: "Quantum Uncertainty", imgName: "Quantum_Uncertainty", level: 8, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 35),
        Card(id: UUID(), name: "Fastest Alive", imgName: "Fastest_Alive", level: 8, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 01),Card(id: UUID(), name: "Reverse The Flow", imgName: "Reverse_The_Flow", level: 9, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 58),
        Card(id: UUID(), name: "Fractured Timeline", imgName: "Fractured_Timeline", level: 9, Unlocked: false, PlayableClass: "Blinkblade", initiativeVal: 55)
    ],
    "deathwalker": [
        Card(id: UUID(), name: "Wave Of Anguish", imgName: "Wave_Of_Anguish", level: 0, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 58), Card(id: UUID(), name: "Rest In The Shade", imgName: "Rest_In_The_Shade", level: 0, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 26),
        Card(id: UUID(), name: "Forceful Spirits", imgName: "Forceful_Spirits", level: 0, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 34), Card(id: UUID(), name: "Call To The Abyss", imgName: "Call_To_The_Abyss", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 82),
        Card(id: UUID(), name: "Anger Of The Dead", imgName: "Anger_Of_The_Dead", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 14), Card(id: UUID(), name: "Sunless Apparition", imgName: "Sunless_Apparition", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 96),
        Card(id: UUID(), name: "Fluid Night", imgName: "Fluid_Night",  level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 24),Card(id: UUID(), name: "Dark Fog", imgName: "Dark_Fog", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 46),
        Card(id: UUID(), name: "Black Barrage", imgName: "Black_Barrage", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 28),Card(id: UUID(), name: "Call Of Doom", imgName: "Call_Of_Doom", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 32),
        Card(id: UUID(), name: "Eclipse", imgName: "Eclipse", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 86),Card(id: UUID(), name: "Lingering Rot", imgName: "Lingering_Rot", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 64),
        Card(id: UUID(), name: "Shadow Step", imgName: "Shadow_Step", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 19),Card(id: UUID(), name: "Strength Of The Abyss", imgName: "Strength_Of_The_Abyss", level: 1, Unlocked: true, PlayableClass: "Deathwalker", initiativeVal: 50),
        Card(id: UUID(), name: "Restless Spirits", imgName: "Restless_Spirits", level: 2, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 20),
        Card(id: UUID(), name: "Deepening Despair", imgName: "Deepening_Despair", level: 2, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 11),Card(id: UUID(), name: "Dead Bolt", imgName: "Dead_Bolt", level: 3, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 88),
        Card(id: UUID(), name: "Ritual Sacrifice", imgName: "Ritual_Sacrifice", level: 3, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 13),Card(id: UUID(), name: "Fleeting Dusk", imgName: "Fleeting_Dusk", level: 4, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 36),
        Card(id: UUID(), name: "Pulled Across", imgName: "Pulled_Across", level: 4, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 77),Card(id: UUID(), name: "Medium", imgName: "Medium", level: 5, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 55),
        Card(id: UUID(), name: "Dominate", imgName: "Dominate", level: 5, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 29),Card(id: UUID(), name: "The Night Takes Shape", imgName: "The_Night_Takes_Shape", level: 6, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 94),
        Card(id: UUID(), name: "Vengeful Storm", imgName: "Vengeful_Storm", level: 6, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 18),Card(id: UUID(), name: "Proliferation Of The Abyss", imgName: "Proliferation_Of_The_Abyss", level: 7, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 38),
        Card(id: UUID(), name: "Hungry Grasps", imgName: "Hungry_Grasps", level: 7, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 25),Card(id: UUID(), name: "Lashing Tendrils", imgName: "Lashing_Tendrils", level: 8, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 80),
        Card(id: UUID(), name: "Frozen In Fear", imgName: "Frozen_In_Fear", level: 8, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 21),Card(id: UUID(), name: "When Your Time Comes", imgName: "When_Your_Time_Comes", level: 9, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 72),
        Card(id: UUID(), name: "Black Lance", imgName: "Black_Lance", level: 9, Unlocked: false, PlayableClass: "Deathwalker", initiativeVal: 16)
    ],
    "snowdancer": [
        Card(id: UUID(), name: "White Winds", imgName: "White_Winds", level: 0, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 11), Card(id: UUID(), name: "Blinding Vortex", imgName: "Blinding_Vortex", level: 0, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 31),
        Card(id: UUID(), name: "The Spirit's Call", imgName: "The_Spirits_Call", level: 0, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 45), Card(id: UUID(), name: "Blizzard", imgName: "Blizzard", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 71),
        Card(id: UUID(), name: "Enticing Breeze", imgName: "Enticing_Breeze", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 76), Card(id: UUID(), name: "Chilling Impact", imgName: "Chilling_Impact", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 31),
        Card(id: UUID(), name: "Gathering Force", imgName: "Gathering_Force",  level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 89),Card(id: UUID(), name: "Nature's Breath", imgName: "Natures_Breath", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 90),
        Card(id: UUID(), name: "Lifting Gust", imgName: "Lifting_Gust", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 27),Card(id: UUID(), name: "Snowball", imgName: "Snowball", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 23),
        Card(id: UUID(), name: "Whiteout", imgName: "Whiteout", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 21),Card(id: UUID(), name: "Cross Winds", imgName: "Cross_Winds", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 32),
        Card(id: UUID(), name: "Frigid Growth", imgName: "Frigid_Growth", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 70),Card(id: UUID(), name: "Cold Therapy", imgName: "Cold_Therapy", level: 1, Unlocked: true, PlayableClass: "Snowdancer", initiativeVal: 20),
        Card(id: UUID(), name: "Birds In A Tempest", imgName: "Birds_In_A_Tempest", level: 2, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 18),
        Card(id: UUID(), name: "Tornado", imgName: "Tornado", level: 2, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 59),Card(id: UUID(), name: "Cold Snap", imgName: "Cold_Snap", level: 3, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 86),
        Card(id: UUID(), name: "Polar_Vortex", imgName: "Polar_Vortex", level: 3, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 61),Card(id: UUID(), name: "Zephyr_Barrier", imgName: "Zephyr_Barrier", level: 4, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 40),
        Card(id: UUID(), name: "Biting Frost", imgName: "Biting_Frost", level: 4, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 16),Card(id: UUID(), name: "Whipping Gale", imgName: "Whipping_Gale", level: 5, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 79),
        Card(id: UUID(), name: "Shifting Snow", imgName: "Shifting_Snow", level: 5, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 17),Card(id: UUID(), name: "Refreshing Flurry", imgName: "Refreshing_Flurry", level: 6, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 95),
        Card(id: UUID(), name: "Frozen Brand", imgName: "Frozen_Brand", level: 6, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 33),Card(id: UUID(), name: "Freezing Storm", imgName: "Freezing_Storm", level: 7, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 81),
        Card(id: UUID(), name: "Storm Wall", imgName: "Storm_Wall", level: 7, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 30),Card(id: UUID(), name: "Surging Blow", imgName: "Surging_Blow", level: 8, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 73),
        Card(id: UUID(), name: "The Endless White", imgName: "The_Endless_White", level: 8, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 05),Card(id: UUID(), name: "Winds Of Change", imgName: "Winds_Of_Change", level: 9, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 15),
        Card(id: UUID(), name: "Snowblind", imgName: "Snowblind", level: 9, Unlocked: false, PlayableClass: "Snowdancer", initiativeVal: 83)
    ],
    "painconduit": [
        Card(id: UUID(), name: "Delayed Malady", imgName: "Delayed_Malady", level: 0, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 90), Card(id: UUID(), name: "Unstable Effigy", imgName: "Unstable_Effigy", level: 0, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 18),
        Card(id: UUID(), name: "Pleasure In Pain", imgName: "Pleasure_In_Pain", level: 0, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 47), Card(id: UUID(), name: "Shared Affliction", imgName: "Shared_Affliction", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 61),
        Card(id: UUID(), name: "Line Of Transference", imgName: "Line_Of_Transference", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 25), Card(id: UUID(), name: "Transferred Injury", imgName: "Transferred_Injury", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 74),
        Card(id: UUID(), name: "The Agony Of Others", imgName: "The_Agony_Of_Others",  level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 78),Card(id: UUID(), name: "Unending Torment", imgName: "Unending_Torment", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 29),
        Card(id: UUID(), name: "Blood Ritual", imgName: "Blood_Ritual", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 56),Card(id: UUID(), name: "Scarred Effigy", imgName: "Scarred_Effigy", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 19),
        Card(id: UUID(), name: "Explosive Wounds", imgName: "Explosive_Wounds", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 43),Card(id: UUID(), name: "Cleansing Fire", imgName: "Cleansing_Fire", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 64),
        Card(id: UUID(), name: "Swift Vengeance", imgName: "Swift_Vengeance", level: 1, Unlocked: true, PlayableClass: "painconduit", initiativeVal: 21),
        
        
        Card(id: UUID(), name: "Reversal Of Fate", imgName: "Reversal_Of_Fate", level: 2, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 23),
        Card(id: UUID(), name: "Infection Purge", imgName: "Infection_Purge", level: 2, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 45),Card(id: UUID(), name: "Burned At Both Ends", imgName: "Burned_At_Both_Ends", level: 3, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 30),
        Card(id: UUID(), name: "Reprisal", imgName: "Reprisal", level: 3, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 70),Card(id: UUID(), name: "Mirrored Misery", imgName: "Mirrored_Misery", level: 4, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 72),
        Card(id: UUID(), name: "Down To The Dirt", imgName: "Down_To_The_Dirt", level: 4, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 39),Card(id: UUID(), name: "Chained By Spite", imgName: "Chained_By_Spite", level: 5, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 15),
        Card(id: UUID(), name: "Chained By Despair", imgName: "Chained_By_Despair", level: 5, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 15),Card(id: UUID(), name: "Hopelessness", imgName: "Hopelessness", level: 6, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 83),
        Card(id: UUID(), name: "Phantom Limb", imgName: "Phantom_Limb", level: 6, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 75),Card(id: UUID(), name: "Reject The Gift", imgName: "Reject_The_Gift", level: 7, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 20),
        Card(id: UUID(), name: "Penance", imgName: "Penance", level: 7, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 12),Card(id: UUID(), name: "Wave Of Anguish", imgName: "Wave_Of_AnguishPC", level: 8, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 68),
        Card(id: UUID(), name: "Wracked With Pain", imgName: "Wracked_With_Pain", level: 8, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 22),Card(id: UUID(), name: "Redemption", imgName: "Redemption", level: 9, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 33),
        Card(id: UUID(), name: "The End Of Everything", imgName: "The_End_Of_Everything", level: 9, Unlocked: false, PlayableClass: "painconduit", initiativeVal: 99)
    ],
    "trapper": [
        Card(id: UUID(), name: "Dismantle", imgName: "Dismantle", level: 0, Unlocked: true, PlayableClass: "trapper", initiativeVal: 72), Card(id: UUID(), name: "Spring-Loaded", imgName: "Spring_Loaded", level: 0, Unlocked: true, PlayableClass: "trapper", initiativeVal: 15),
        Card(id: UUID(), name: "Improvised Improvement", imgName: "Improvised_Improvement", level: 0, Unlocked: true, PlayableClass: "trapper", initiativeVal: 58), Card(id: UUID(), name: "Caltrops", imgName: "Caltrops", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 25),
        Card(id: UUID(), name: "Flurry Facade", imgName: "Flurry_Facade", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 85), Card(id: UUID(), name: "Boar Catcher", imgName: "Boar_Catcher", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 20),
        Card(id: UUID(), name: "Spike Pit", imgName: "Spike_Pit",  level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 47),Card(id: UUID(), name: "Electrified Net", imgName: "Electrified_Net", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 53),
        Card(id: UUID(), name: "Honeypot", imgName: "Honeypot", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 18),Card(id: UUID(), name: "Enticing Bait", imgName: "Enticing_Bait", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 30),
        Card(id: UUID(), name: "Exploding Decoy", imgName: "Exploding_Decoy", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 62),Card(id: UUID(), name: "Flurry Of Nails", imgName: "Flurry_Of_Nails", level: 1, Unlocked: true, PlayableClass: "trapper", initiativeVal: 68),
        
        Card(id: UUID(), name: "Unavoidable Outcome", imgName: "Unavoidable_Outcome", level: 2, Unlocked: false, PlayableClass: "trapper", initiativeVal: 45),
        Card(id: UUID(), name: "Path Of Pain", imgName: "Path_Of_Pain", level: 2, Unlocked: false, PlayableClass: "trapper", initiativeVal: 38),Card(id: UUID(), name: "Extra Teeth", imgName: "Extra_Teeth", level: 3, Unlocked: false, PlayableClass: "trapper", initiativeVal: 22),
        Card(id: UUID(), name: "Pyrotechnics", imgName: "Pyrotechnics", level: 3, Unlocked: false, PlayableClass: "trapper", initiativeVal: 80),Card(id: UUID(), name: "Dangerous Ground", imgName: "Dangerous_Ground", level: 4, Unlocked: false, PlayableClass: "trapper", initiativeVal: 31),
        Card(id: UUID(), name: "Stalker's Spoils", imgName: "Stalkers_Spoils", level: 4, Unlocked: false, PlayableClass: "trapper", initiativeVal: 10),Card(id: UUID(), name: "Lure Of The Snare", imgName: "Lure_Of_The_Snare", level: 5, Unlocked: false, PlayableClass: "trapper", initiativeVal: 59),
        Card(id: UUID(), name: "Proficient Hunter", imgName: "Proficient_Hunter", level: 5, Unlocked: false, PlayableClass: "trapper", initiativeVal: 26),Card(id: UUID(), name: "Persistent Pitfalls", imgName: "Persistent_Pitfalls", level: 6, Unlocked: false, PlayableClass: "trapper", initiativeVal: 13),
        Card(id: UUID(), name: "Cage Of Thorns", imgName: "Cage_Of_Thorns", level: 6, Unlocked: false, PlayableClass: "trapper", initiativeVal: 55),Card(id: UUID(), name: "Grasping Hazards", imgName: "Grasping_Hazards", level: 7, Unlocked: false, PlayableClass: "trapper", initiativeVal: 08),
        Card(id: UUID(), name: "Foxhole", imgName: "Foxhole", level: 7, Unlocked: false, PlayableClass: "trapper", initiativeVal: 90),Card(id: UUID(), name: "Spike Strip", imgName: "Spike_Strip", level: 8, Unlocked: false, PlayableClass: "trapper", initiativeVal: 67),
        Card(id: UUID(), name: "Magnetic Shards", imgName: "Magnetic_Shards", level: 8, Unlocked: false, PlayableClass: "trapper", initiativeVal: 37),Card(id: UUID(), name: "Dangerous Cargo", imgName: "Dangerous_Cargo", level: 9, Unlocked: false, PlayableClass: "trapper", initiativeVal: 23),
        Card(id: UUID(), name: "Mother Of All Traps", imgName: "Mother_Of_All_Traps", level: 9, Unlocked: false, PlayableClass: "trapper", initiativeVal: 86)
    ],
    "shattersong": [
        Card(id: UUID(), name: "Calamitous Yawp", imgName: "Calamitous_Yawp", level: 0, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 65), Card(id: UUID(), name: "Din Of Battle", imgName: "Din_Of_Battle", level: 0, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 14),
        Card(id: UUID(), name: "Illuminative Tone", imgName: "Illuminative_Tone", level: 0, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 72), Card(id: UUID(), name: "Unrelenting Wail", imgName: "Unrelenting_Wail", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 26),
        Card(id: UUID(), name: "Lifting Voice", imgName: "Lifting_Voice", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 29), Card(id: UUID(), name: "Heartening Harmony", imgName: "Heartening_Harmony", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 30),
        Card(id: UUID(), name: "Forceful Vibrations", imgName: "Forceful_Vibrations",  level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 27),Card(id: UUID(), name: "Resonant Frequency", imgName: "Resonant_Frequency", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 88),
        Card(id: UUID(), name: "Foreboding Tremors", imgName: "Foreboding_Tremors", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 21),Card(id: UUID(), name: "Sonic Shock", imgName: "Sonic_Shock", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 58),
        Card(id: UUID(), name: "Precious Gems", imgName: "Precious_Gems", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 10),Card(id: UUID(), name: "Empowering Pulse", imgName: "Empowering_Pulse", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 22),
        Card(id: UUID(), name: "Devastating Shout", imgName: "Devastating_Shout", level: 1, Unlocked: true, PlayableClass: "shattersong", initiativeVal: 68),
        Card(id: UUID(), name: "Transparency", imgName: "Transparency", level: 2, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 13),Card(id: UUID(), name: "Befuddling Bellow", imgName: "Befuddling_Bellow", level: 2, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 18),
        Card(id: UUID(), name: "Shape The Path", imgName: "Shape_The_Path", level: 3, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 40),Card(id: UUID(), name: "Stealth Vibrations", imgName: "Stealth_Vibrations", level: 3, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 35),
        Card(id: UUID(), name: "Concentrated Blast", imgName: "Concentrated_Blast", level: 4, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 38),Card(id: UUID(), name: "Elemental Pulse", imgName: "Elemental_Pulse", level: 4, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 25),
        Card(id: UUID(), name: "Shrieking Chakram", imgName: "Shrieking_Chakram", level: 5, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 08),Card(id: UUID(), name: "Empowering Note", imgName: "Empowering_Note", level: 5, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 45),
        Card(id: UUID(), name: "Unsustainable Wave", imgName: "Unsustainable_Wave", level: 6, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 36),
        Card(id: UUID(), name: "Future Sense", imgName: "Future_Sense", level: 6, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 28),Card(id: UUID(), name: "Sound Therapy", imgName: "Sound_Therapy", level: 7, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 73),
        Card(id: UUID(), name: "Cloaking Refraction", imgName: "Cloaking_Refraction", level: 7, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 11),Card(id: UUID(), name: "Soft Spots", imgName: "Soft_Spots", level: 8, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 47),
        Card(id: UUID(), name: "Feedback", imgName: "Feedback", level: 8, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 24),Card(id: UUID(), name: "Barbaric Yawp", imgName: "Barbaric_Yawp", level: 9, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 66),
        Card(id: UUID(), name: "Violent Vibrations", imgName: "Violent_Vibrations", level: 9, Unlocked: false, PlayableClass: "shattersong", initiativeVal: 05)
    ],
    "pyroclast": [
        Card(id: UUID(), name: "Wildfire", imgName: "Wildfire", level: 0, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 72), Card(id: UUID(), name: "Force Of The Earth", imgName: "Force_Of_The_Earth", level: 0, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 15),
        Card(id: UUID(), name: "Metamorphic Rock", imgName: "Metamorphic_Rock", level: 0, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 68), Card(id: UUID(), name: "Cooling", imgName: "Cooling", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 75),
        Card(id: UUID(), name: "Quenched Rage", imgName: "Quenched_Rage", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 30), Card(id: UUID(), name: "Flowing Fire", imgName: "Flowing_Fire", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 20),
        Card(id: UUID(), name: "Eruption", imgName: "Eruption",  level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 47),Card(id: UUID(), name: "Lava Bomb", imgName: "Lava_Bomb", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 53),
        Card(id: UUID(), name: "Igneous Path", imgName: "Igneous_Path", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 18),Card(id: UUID(), name: "Under Pressure", imgName: "Under_Pressure", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 85),
        Card(id: UUID(), name: "Melted Armor", imgName: "Melted_Armor", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 62),Card(id: UUID(), name: "Liquid Stone", imgName: "Liquid_Stone", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 28),
        Card(id: UUID(), name: "Cloud Of Ash", imgName: "Cloud_Of_Ash", level: 1, Unlocked: true, PlayableClass: "pyroclast", initiativeVal: 23),
        Card(id: UUID(), name: "Searing Smoke", imgName: "Searing_Smoke", level: 2, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 45),Card(id: UUID(), name: "Deep Fury", imgName: "Deep_Fury", level: 2, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 38),
        Card(id: UUID(), name: "Living Magma", imgName: "Living_Magma", level: 3, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 22),Card(id: UUID(), name: "Hardened Spike", imgName: "Hardened_Spike", level: 3, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 80),
        Card(id: UUID(), name: "Hand Of Flame", imgName: "Hand_Of_Flame", level: 4, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 29),Card(id: UUID(), name: "Heat Wave", imgName: "Heat_Wave", level: 4, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 08),
        Card(id: UUID(), name: "Rain Of Fire", imgName: "Rain_Of_Fire", level: 5, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 21),Card(id: UUID(), name: "Magma Orbs", imgName: "Magma_Orbs", level: 5, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 82),
        Card(id: UUID(), name: "Return To The Source", imgName: "Return_To_The_Source", level: 6, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 14),
        Card(id: UUID(), name: "Obsidian Shield", imgName: "Obsidian_Shield", level: 6, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 19),Card(id: UUID(), name: "Erupting Rage", imgName: "Erupting_Rage", level: 7, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 70),
        Card(id: UUID(), name: "Swelter", imgName: "Swelter", level: 7, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 32),Card(id: UUID(), name: "Feed The Beast", imgName: "Feed_The_Beast", level: 8, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 27),
        Card(id: UUID(), name: "Cinder Lance", imgName: "Cinder_Lance", level: 8, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 90),Card(id: UUID(), name: "Stone Armor", imgName: "Stone_Armor", level: 9, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 09),
        Card(id: UUID(), name: "Calamity", imgName: "Calamity", level: 9, Unlocked: false, PlayableClass: "pyroclast", initiativeVal: 35)
    ],
    "infuser": [
        Card(id: UUID(), name: "Imbue With Life", imgName: "Imbue_With_Life", level: 0, Unlocked: true, PlayableClass: "infuser", initiativeVal: 42),
        Card(id: UUID(), name: "Battle Prowess", imgName: "Battle_Prowess", level: 0, Unlocked: true, PlayableClass: "infuser", initiativeVal: 78),
        Card(id: UUID(), name: "Crystalline Aegis", imgName: "Crystalline_Aegis", level: 0, Unlocked: true, PlayableClass: "infuser", initiativeVal: 17),
        Card(id: UUID(), name: "Boon Of The Tempest", imgName: "Boon_Of_The_Tempest", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 28),
        Card(id: UUID(), name: "Bounty Of The Earth", imgName: "Bounty_Of_The_Earth", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 23),
        Card(id: UUID(), name: "Caress Of The Night", imgName: "Caress_Of_The_Night", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 87),
        Card(id: UUID(), name: "Formless Bladestorm", imgName: "Formless_Bladestorm",  level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 33),
        Card(id: UUID(), name: "Emerald Edge", imgName: "Emerald_Edge", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 70),
        Card(id: UUID(), name: "Torrential Cleave", imgName: "Torrential_Cleave", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 83),
        Card(id: UUID(), name: "Onyx Shards", imgName: "Onyx_Shards", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 20),
        Card(id: UUID(), name: "Unstoppable Impulse", imgName: "Unstoppable_Impulse", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 56),
        Card(id: UUID(), name: "Slashing Cyclone", imgName: "Slashing_Cyclone", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 14),
        Card(id: UUID(), name: "Rising Momentum", imgName: "Rising_Momentum", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 25),
        Card(id: UUID(), name: "Stoic Vigilance", imgName: "Stoic_Vigilance", level: 1, Unlocked: true, PlayableClass: "infuser", initiativeVal: 12),
        
        Card(id: UUID(), name: "Veil Of Protection", imgName: "Veil_Of_Protection", level: 2, Unlocked: false, PlayableClass: "infuser", initiativeVal: 47),
        Card(id: UUID(), name: "Remote Impact", imgName: "Remote_Impact", level: 2, Unlocked: false, PlayableClass: "infuser", initiativeVal: 72),
        Card(id: UUID(), name: "Reinforced Riposte", imgName: "Reinforced_Riposte", level: 3, Unlocked: false, PlayableClass: "infuser", initiativeVal: 18),
        Card(id: UUID(), name: "Guide The Flow", imgName: "Guide_The_Flow", level: 3, Unlocked: false, PlayableClass: "infuser", initiativeVal: 35),
        Card(id: UUID(), name: "Coalescing Darkness", imgName: "Coalescing_Darkness", level: 4, Unlocked: false, PlayableClass: "infuser", initiativeVal: 85),
        Card(id: UUID(), name: "Desperate Throw", imgName: "Desperate_Throw", level: 4, Unlocked: false, PlayableClass: "infuser", initiativeVal: 16),
        Card(id: UUID(), name: "Gemstone Resonance", imgName: "Gemstone_Resonance", level: 5, Unlocked: false, PlayableClass: "infuser", initiativeVal: 30),
        Card(id: UUID(), name: "Obsidian Spear", imgName: "Obsidian_Spear", level: 5, Unlocked: false, PlayableClass: "infuser", initiativeVal: 84),
        Card(id: UUID(), name: "Propulsive Tailwind", imgName: "Propulsive_Tailwind", level: 6, Unlocked: false, PlayableClass: "infuser", initiativeVal: 91),
        Card(id: UUID(), name: "Gale_Barrage", imgName: "Gale_Barrage", level: 6, Unlocked: false, PlayableClass: "infuser", initiativeVal: 44),
        Card(id: UUID(), name: "Diamondization", imgName: "Diamondization", level: 7, Unlocked: false, PlayableClass: "infuser", initiativeVal: 10),
        Card(id: UUID(), name: "Malachite Shockwave", imgName: "Malachite_Shockwave", level: 7, Unlocked: false, PlayableClass: "infuser", initiativeVal: 68),
        Card(id: UUID(), name: "Untether The Shackles", imgName: "Untether_The_Shackles", level: 8, Unlocked: false, PlayableClass: "infuser", initiativeVal: 61),
        Card(id: UUID(), name: "Swift Pivot", imgName: "Swift_Pivot", level: 8, Unlocked: false, PlayableClass: "infuser", initiativeVal: 08),
        Card(id: UUID(), name: "Ancient Rites Of Power", imgName: "Ancient_Rites_Of_Power", level: 9, Unlocked: false, PlayableClass: "infuser", initiativeVal: 94),
        Card(id: UUID(), name: "Sky-Splitting Strike", imgName: "Sky_Splitting_Strike", level: 9, Unlocked: false, PlayableClass: "infuser", initiativeVal: 50)
    ],
    "crashingtide": [
        Card(id: UUID(), name: "Rising Flood", imgName: "Rising_Flood", level: 0, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 49),
        Card(id: UUID(), name: "Undertow", imgName: "Undertow", level: 0, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 15),
        Card(id: UUID(), name: "Crush Armor", imgName: "Crush_Armor", level: 0, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 42),
        Card(id: UUID(), name: "Overwhelming Wave", imgName: "Overwhelming_Wave", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 86),
        Card(id: UUID(), name: "Soft Flesh", imgName: "Soft_Flesh", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 75),
        Card(id: UUID(), name: "Rancid Brine", imgName: "Rancid_Brine", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 62),
        Card(id: UUID(), name: "Sharp Chitin", imgName: "Sharp_Chitin",  level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 25),
        Card(id: UUID(), name: "Down To The Depths", imgName: "Down_To_The_Depths", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 74),
        Card(id: UUID(), name: "Pool Of Power", imgName: "Pool_Of_Power", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 41),
        Card(id: UUID(), name: "Skitter", imgName: "Skitter", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 51),
        Card(id: UUID(), name: "Cleaning Swell", imgName: "Cleansing_Swell", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 45),
        Card(id: UUID(), name: "Cresting Force", imgName: "Cresting_Force", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 87),
        Card(id: UUID(), name: "Crashing Surge", imgName: "Crashing_Surge", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 34),
        Card(id: UUID(), name: "Mighty Claws", imgName: "Mighty_Claws", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 23),
        Card(id: UUID(), name: "Submerge", imgName: "Submerge", level: 1, Unlocked: true, PlayableClass: "crashingtide", initiativeVal: 68),
        
        Card(id: UUID(), name: "Smashing Torrent", imgName: "Smashing_Torrent", level: 2, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 79),
        Card(id: UUID(), name: "Blood In The Water", imgName: "Blood_In_The_Water", level: 2, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 53),
        Card(id: UUID(), name: "Shuck", imgName: "Shuck", level: 3, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 55),
        Card(id: UUID(), name: "Endless Cycle", imgName: "Endless_Cycle", level: 3, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 08),
        Card(id: UUID(), name: "Chaotic Refraction", imgName: "Chaotic_Refraction", level: 4, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 26),
        Card(id: UUID(), name: "Clean Sweep", imgName: "Clean_Sweep", level: 4, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 65),
        Card(id: UUID(), name: "Tidal Blast", imgName: "Tidal_Blast", level: 5, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 71),
        Card(id: UUID(), name: "Sodden Soil", imgName: "Sodden_Soil", level: 5, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 17),
        Card(id: UUID(), name: "Powerful Pincer", imgName: "Powerful_Pincer", level: 6, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 70),
        Card(id: UUID(), name: "Twilight Grasp", imgName: "Twilight_Grasp", level: 6, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 33),
        Card(id: UUID(), name: "Dug In", imgName: "Dug_In", level: 7, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 76),
        Card(id: UUID(), name: "Drown_Beneath_The_Waves", imgName: "Drown_Beneath_The_Waves", level: 7, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 09),
        Card(id: UUID(), name: "Death On All Sides", imgName: "Death_On_All_Sides", level: 8, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 73),
        Card(id: UUID(), name: "Ebb And Flow", imgName: "Ebb_And_Flow", level: 8, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 24),
        Card(id: UUID(), name: "High Tide", imgName: "High_Tide", level: 9, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 90),
        Card(id: UUID(), name: "Low Tide", imgName: "Low_Tide", level: 9, Unlocked: false, PlayableClass: "crashingtide", initiativeVal: 10)
    ],
    "deepwraith": [
        Card(id: UUID(), name: "Soul Hunger", imgName: "Soul_Hunger", level: 0, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 91),
        Card(id: UUID(), name: "Morbid Camouflage", imgName: "Morbid_Camouflage", level: 0, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 31),
        Card(id: UUID(), name: "Haunting Brutality", imgName: "Haunting_Brutality", level: 0, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 23),
        Card(id: UUID(), name: "Skull Collection", imgName: "Skull_Collection", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 22),
        Card(id: UUID(), name: "Hollow Aura", imgName: "Hollow_Aura", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 88),
        Card(id: UUID(), name: "Skewer The Flesh", imgName: "Skewer_The_Flesh", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 86),
        Card(id: UUID(), name: "Succumb To Fear", imgName: "Succumb_To_Fear",  level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 20),
        Card(id: UUID(), name: "Ink Cloud", imgName: "Ink_Cloud", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 28),
        Card(id: UUID(), name: "Lacerating Stabs", imgName: "Lacerating_Stabs", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 14),
        Card(id: UUID(), name: "Staring Into The Abyss", imgName: "Staring_Into_The_Abyss", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 63),
        Card(id: UUID(), name: "Mantle Of Dread", imgName: "Mantle_Of_Dread", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 96),
        Card(id: UUID(), name: "Black Scythe", imgName: "Black_Scythe", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 45),
        Card(id: UUID(), name: "Tumultuous Panic", imgName: "Tumultuous_Panic", level: 1, Unlocked: true, PlayableClass: "deepwraith", initiativeVal: 66),
        
        
        Card(id: UUID(), name: "Slipping Into Death", imgName: "Slipping_Into_Death", level: 2, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 89),
        Card(id: UUID(), name: "Lie In Wait", imgName: "Lie_In_Wait", level: 2, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 98),
        Card(id: UUID(), name: "Crippling Terror", imgName: "Crippling_Terror", level: 3, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 15),
        Card(id: UUID(), name: "Pinning Spines", imgName: "Pinning_Spines", level: 3, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 25),
        Card(id: UUID(), name: "Crushing Darkness", imgName: "Crushing_Darkness", level: 4, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 40),
        Card(id: UUID(), name: "Grim Trophies", imgName: "Grim_Trophies", level: 4, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 18),
        Card(id: UUID(), name: "Extra Decoration", imgName: "Extra_Decoration", level: 5, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 92),
        Card(id: UUID(), name: "Death Spiral", imgName: "Death_Spiral", level: 5, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 48),
        Card(id: UUID(), name: "Claw Of Doom", imgName: "Claw_Of_Doom", level: 6, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 30),
        Card(id: UUID(), name: "The Remorseless Deep", imgName: "The_Remorseless_Deep", level: 6, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 22),
        Card(id: UUID(), name: "Hasten The End", imgName: "Hasten_The_End", level: 7, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 65),
        Card(id: UUID(), name: "Dire Frenzy", imgName: "Dire_Frenzy", level: 7, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 26),
        Card(id: UUID(), name: "Unseen Horror", imgName: "Unseen_Horror", level: 8, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 19),
        Card(id: UUID(), name: "Rip From The Bone", imgName: "Rip_From_The_Bone", level: 8, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 11),
        Card(id: UUID(), name: "Black Night Of The Deep", imgName: "Black_Night_Of_The_Deep", level: 9, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 26),
        Card(id: UUID(), name: "Consume The Helpless", imgName: "Consume_The_Helpless", level: 9, Unlocked: false, PlayableClass: "deepwraith", initiativeVal: 12)
    ],
    "metalmosaic": [
        Card(id: UUID(), name: "Processing", imgName: "Processing", level: 0, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 95),
        Card(id: UUID(), name: "Recursion", imgName: "Recursion", level: 0, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 50),
        Card(id: UUID(), name: "Curious Gear", imgName: "Curious_Gear", level: 0, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 12),
        Card(id: UUID(), name: "Steam Armor", imgName: "Steam_Armor", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 17),
        Card(id: UUID(), name: "Ancient Drill", imgName: "Ancient_Drill", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 90),
        Card(id: UUID(), name: "Rocket Boots", imgName: "Rocket_Boots", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 22),
        Card(id: UUID(), name: "Power Core", imgName: "Power_Core",  level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 83),
        Card(id: UUID(), name: "Steel Piston", imgName: "Steel_Piston", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 40),
        Card(id: UUID(), name: "Pressure Build-Up", imgName: "Pressure_Build_Up", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 20),
        Card(id: UUID(), name: "Beam Axe", imgName: "Beam_Axe", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 29),
        Card(id: UUID(), name: "Memory Drive", imgName: "Memory_Drive", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 64),
        Card(id: UUID(), name: "Super Heat Transfer", imgName: "Super_Heat_Transfer", level: 1, Unlocked: true, PlayableClass: "metalmosaic", initiativeVal: 25),
        
        
        Card(id: UUID(), name: "Release Valve", imgName: "Release_Valve", level: 2, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 30),
        Card(id: UUID(), name: "Bronze Plating", imgName: "Bronze_Plating", level: 2, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 18),
        Card(id: UUID(), name: "Stress Vents", imgName: "Stress_Vents", level: 3, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 15),
        Card(id: UUID(), name: "Electrical Discharge", imgName: "Electrical_Discharge", level: 3, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 26),
        Card(id: UUID(), name: "Energy Conversion", imgName: "Energy_Conversion", level: 4, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 23),
        Card(id: UUID(), name: "Magnetic Field", imgName: "Magnetic_Field", level: 4, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 21),
        Card(id: UUID(), name: "Radiation", imgName: "Radiation", level: 5, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 37),
        Card(id: UUID(), name: "Heat Conduction", imgName: "Heat_Conduction", level: 5, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 11),
        Card(id: UUID(), name: "Scalding Blast", imgName: "Scalding_Blast", level: 6, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 45),
        Card(id: UUID(), name: "Steam Core", imgName: "Steam_Core", level: 6, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 71),
        Card(id: UUID(), name: "Heated Drill", imgName: "Heated_Drill", level: 7, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 80),
        Card(id: UUID(), name: "Cryogenic Hibernation", imgName: "Cryogenic_Hibernation", level: 7, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 19),
        Card(id: UUID(), name: "Piston Barrage", imgName: "Piston_Barrage", level: 8, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 33),
        Card(id: UUID(), name: "Curious Machinery", imgName: "Curious_Machinery", level: 8, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 11),
        Card(id: UUID(), name: "Polarity Shift", imgName: "Polarity_Shift", level: 9, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 79),
        Card(id: UUID(), name: "Unstable Core", imgName: "Unstable_Core", level: 9, Unlocked: false, PlayableClass: "metalmosaic", initiativeVal: 10)
    ],
    "hive": [
        Card(id: UUID(), name: "Shocking Pulse", imgName: "Shocking_Pulse", level: 0, Unlocked: true, PlayableClass: "hive", initiativeVal: 56),
        Card(id: UUID(), name: "Remote Control", imgName: "Remote_Control", level: 0, Unlocked: true, PlayableClass: "hive", initiativeVal: 48),
        Card(id: UUID(), name: "Reassemble", imgName: "Reassemble", level: 0, Unlocked: true, PlayableClass: "hive", initiativeVal: 27),
        Card(id: UUID(), name: "Plated Defense", imgName: "Plated_Defense", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 80),
        Card(id: UUID(), name: "Reconstructive Aid", imgName: "Reconstructive_Aid", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 90),
        Card(id: UUID(), name: "Hunter-Killer", imgName: "Hunter_Killer", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 84),
        Card(id: UUID(), name: "Coiled Limbs", imgName: "Coiled_Limbs",  level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 82),
        Card(id: UUID(), name: "Aimed_Assault", imgName: "Aimed_Assault", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 88),
        Card(id: UUID(), name: "Launch Pod", imgName: "Launch_Pod", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 77),
        Card(id: UUID(), name: "Faceless Entity", imgName: "Faceless_Entity", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 12),
        Card(id: UUID(), name: "Prepare For Deployment", imgName: "Prepare_For_Deployment", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 64),
        Card(id: UUID(), name: "Reaper Function", imgName: "Reaper_Function", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 32),
        Card(id: UUID(), name: "High Impact Projectiles", imgName: "High_Impact_Projectiles", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 16),
        Card(id: UUID(), name: "Interference", imgName: "Interference", level: 1, Unlocked: true, PlayableClass: "hive", initiativeVal: 21),
        
        Card(id: UUID(), name: "Force Field", imgName: "Force_Field", level: 2, Unlocked: false, PlayableClass: "hive", initiativeVal: 78),
        Card(id: UUID(), name: "Long-Range Missile", imgName: "Long_Range_Missile", level: 2, Unlocked: false, PlayableClass: "hive", initiativeVal: 19),
        Card(id: UUID(), name: "Rapid Fire", imgName: "Rapid_Fire", level: 3, Unlocked: false, PlayableClass: "hive", initiativeVal: 92),
        Card(id: UUID(), name: "Hijack", imgName: "Hijack", level: 3, Unlocked: false, PlayableClass: "hive", initiativeVal: 40),
        Card(id: UUID(), name: "Plague Protocol", imgName: "Plague_Protocol", level: 4, Unlocked: false, PlayableClass: "hive", initiativeVal: 98),
        Card(id: UUID(), name: "Divergent Destruction", imgName: "Divergent_Destruction", level: 4, Unlocked: false, PlayableClass: "hive", initiativeVal: 22),
        Card(id: UUID(), name: "Net Dispersal", imgName: "Net_Dispersal", level: 5, Unlocked: false, PlayableClass: "hive", initiativeVal: 94),
        Card(id: UUID(), name: "Code Geminate", imgName: "Code_Geminate", level: 5, Unlocked: false, PlayableClass: "hive", initiativeVal: 28),
        Card(id: UUID(), name: "Spinning Blades", imgName: "Spinning_Blades", level: 6, Unlocked: false, PlayableClass: "hive", initiativeVal: 79),
        Card(id: UUID(), name: "Triage Program", imgName: "Triage_Program", level: 6, Unlocked: false, PlayableClass: "hive", initiativeVal: 13),
        Card(id: UUID(), name: "Mortar Shells", imgName: "Mortar_Shells", level: 7, Unlocked: false, PlayableClass: "hive", initiativeVal: 85),
        Card(id: UUID(), name: "Recall", imgName: "Recall", level: 7, Unlocked: false, PlayableClass: "hive", initiativeVal: 91),
        Card(id: UUID(), name: "Swarming Bulwark", imgName: "Swarming_Bulwark", level: 8, Unlocked: false, PlayableClass: "hive", initiativeVal: 96),
        Card(id: UUID(), name: "Burning Slash", imgName: "Burning_Slash", level: 8, Unlocked: false, PlayableClass: "hive", initiativeVal: 29),
        Card(id: UUID(), name: "Heavy Metal", imgName: "Heavy_Metal", level: 9, Unlocked: false, PlayableClass: "hive", initiativeVal: 76),
        Card(id: UUID(), name: "Disassemble", imgName: "Disassemble", level: 9, Unlocked: false, PlayableClass: "hive", initiativeVal: 20)
    ],
    "frozenfist": [
        Card(id: UUID(), name: "Shard Launch", imgName: "Shard_Launch", level: 0, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 52),
        Card(id: UUID(), name: "Primal Bellow", imgName: "Primal_Bellow", level: 0, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 84),
        Card(id: UUID(), name: "Freezing Shell", imgName: "Freezing_Shell", level: 0, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 17),
        Card(id: UUID(), name: "One With The Mountain", imgName: "One_With_The_Mountain", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 83),
        Card(id: UUID(), name: "Cold Boulder", imgName: "Cold_Boulder", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 70),
        Card(id: UUID(), name: "Frost Eruption", imgName: "Frost_Eruption", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 61),
        Card(id: UUID(), name: "Fury Of The Mountain", imgName: "Fury_Of_The_Mountain",  level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 23),
        Card(id: UUID(), name: "Encased Punch", imgName: "Encased_Punch", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 19),
        Card(id: UUID(), name: "Voice From Below", imgName: "Voice_From_Below", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 22),
        Card(id: UUID(), name: "Piercing Pummel", imgName: "Piercing_Pummel", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 30),
        Card(id: UUID(), name: "Ice Blast", imgName: "Ice_Blast", level: 1, Unlocked: true, PlayableClass: "frozenfist", initiativeVal: 32),
     
        
        
        Card(id: UUID(), name: "Draw Of The Bedrock", imgName: "Draw_Of_The_Bedrock", level: 2, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 10),
        Card(id: UUID(), name: "Crushing_Crystals", imgName: "Crushing_Crystals", level: 2, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 67),
        Card(id: UUID(), name: "Lacerating Eruption", imgName: "Lacerating_Eruption", level: 3, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 51),
        Card(id: UUID(), name: "Frozen Over", imgName: "Frozen_Over", level: 3, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 20),
        Card(id: UUID(), name: "The Mountain's Fist", imgName: "The_Mountains_Fist", level: 4, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 16),
        Card(id: UUID(), name: "Packed Solid", imgName: "Packed_Solid", level: 4, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 55),
        Card(id: UUID(), name: "Preserved Fury", imgName: "Preserved_Fury", level: 5, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 49),
        Card(id: UUID(), name: "Ice Uppercut", imgName: "Ice_Uppercut", level: 5, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 15),
        Card(id: UUID(), name: "Thick Frost", imgName: "Thick_Frost", level: 6, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 21),
        Card(id: UUID(), name: "Glacier Slam", imgName: "Glacier_Slam", level: 6, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 84),
        Card(id: UUID(), name: "Gift Of The Mountain", imgName: "Gift_Of_The_Mountain", level: 7, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 73),
        Card(id: UUID(), name: "Seeing Stars", imgName: "Seeing_Stars", level: 7, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 29),
        Card(id: UUID(), name: "Shattering Blow", imgName: "Shattering_Blow", level: 8, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 18),
        Card(id: UUID(), name: "Draw Strength", imgName: "Draw_Strength", level: 8, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 28),
        Card(id: UUID(), name: "Bring Down The Mountain", imgName: "Bring_Down_The_Mountain", level: 9, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 9),
        Card(id: UUID(), name: "Frozen Spike", imgName: "Frozen_Spike", level: 9, Unlocked: false, PlayableClass: "frozenfist", initiativeVal: 33)
    ],
    
]

